version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: deviceapi-postgres
    environment:
      POSTGRES_DB: devicedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  device-api:
    build:
        context: ./
        dockerfile: Dockerfile
    container_name: device-management-api
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/devicedb
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: