spring:
  application:
    name: device-management-api

  datasource:
    url: jdbc:postgresql://localhost:5432/devicedb
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  profiles:
    active: ${ACTIVE_PROFILE:local}

server:
  port: ${SERVER_PORT:8080}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.deviceapi: DEBUG
    org.springframework.web: INFO
